---
title: Clean Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
header-img: img/home-bg.jpg
email: admin@chipandjoannaexposed.com
copyright_name: Chipandjoannaexposed.com
description: This is where the site description goes.
baseurl: "/chipandjoannaexposed.com"
url: http://chipandjoannaexposed.com
twitter_username: 
github_username: 
facebook_username: 
email_username: admin@chipandjoanna.com
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude:
- less
- node_modules
- Gruntfile.js
- package.json
- README.md
gems:
- jekyll-paginate
- jekyll-feed
